"""Generate VAPID key pair untuk Web Push.

Output ditulis ke stdout dalam format env-friendly. User tinggal copy
ke .env (line VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY).

Idempotent: kalau .env sudah ada VAPID_PUBLIC_KEY isinya, script akan
exit tanpa override (kecuali --force).
"""
from __future__ import annotations

import base64
import sys
from pathlib import Path

from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec


def _b64url(b: bytes) -> str:
    return base64.urlsafe_b64encode(b).decode("ascii").rstrip("=")


def main() -> int:
    force = "--force" in sys.argv
    env_path = Path(__file__).parent / ".env"

    if env_path.exists() and not force:
        existing = env_path.read_text(encoding="utf-8")
        if "VAPID_PRIVATE_KEY=" in existing and "VAPID_PUBLIC_KEY=" in existing:
            # Already configured. Print existing public key for convenience.
            for line in existing.splitlines():
                if line.startswith("VAPID_PUBLIC_KEY="):
                    print("VAPID keys already exist in .env. Public:")
                    print(line.split("=", 1)[1].strip())
                    print("(use --force to regenerate)")
                    return 0

    private_key = ec.generate_private_key(ec.SECP256R1(), backend=default_backend())

    # Private key as raw 32-byte scalar → base64url
    priv_int = private_key.private_numbers().private_value
    priv_bytes = priv_int.to_bytes(32, "big")
    private_b64 = _b64url(priv_bytes)

    # Public key as uncompressed point (65 bytes: 0x04 || X(32) || Y(32))
    pub_bytes = private_key.public_key().public_bytes(
        encoding=serialization.Encoding.X962,
        format=serialization.PublicFormat.UncompressedPoint,
    )
    public_b64 = _b64url(pub_bytes)

    # Write/append to .env
    lines: list[str] = []
    if env_path.exists():
        for line in env_path.read_text(encoding="utf-8").splitlines():
            if line.startswith("VAPID_PUBLIC_KEY=") or line.startswith("VAPID_PRIVATE_KEY=") or line.startswith("VAPID_SUBJECT="):
                continue
            lines.append(line)
    lines.append("")
    lines.append("# Web Push VAPID keys (generated by _gen_vapid.py)")
    lines.append(f"VAPID_PUBLIC_KEY={public_b64}")
    lines.append(f"VAPID_PRIVATE_KEY={private_b64}")
    lines.append("VAPID_SUBJECT=mailto:admin@aethera.my.id")
    env_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

    print("VAPID keys generated and written to .env")
    print(f"  VAPID_PUBLIC_KEY={public_b64}")
    print(f"  (private key length: {len(private_b64)} chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
